// import { createReadStream } from "fs";
// import { parse } from "csv-parse";

// async function readCSV() {
//     let data = [];
//     createReadStream("./src/city_cost_of_living_data.csv")
//         .pipe(parse({ delimiter: ",", from_line: 2 }))
//         .on("data", function (row) {
//             data.push(row);
//             console.log(row, ",");
//         })
//         .on("end", function () {
//             // This code block will execute when parsing is complete
//             console.log("Finished");
//         });
// }

const citiesNestedArray = [
    ["1st", "London (United Kingdom)", "240"],
    ["2nd", "New York City (United States)", "226"],
    ["3rd", "Grand Cayman (Cayman Islands)", "225"],
    ["4th", "Zurich (Switzerland)", "218"],
    ["5th", "Geneva (Switzerland)", "208"],
    ["6th", "Miami, Florida (United States)", "207"],
    ["7th", "Boston, Massachusetts (United States)", "203"],
    ["8th", "San Jose, California (United States)", "202"],
    ["9th", "Basel (Switzerland)", "199"],
    ["10th", "Lausanne (Switzerland)", "198"],
    ["11th", "Singapore", "194"],
    ["12th", "Lugano (Switzerland)", "190"],
    ["13th", "Denver, Colorado (United States)", "185"],
    ["14th", "Los Angeles, California (United States)", "185"],
    ["15th", "Sydney (Australia)", "184"],
    ["16th", "Atlanta, Georgia (United States)", "181"],
    ["17th", "Seattle, Washington (United States)", "175"],
    ["18th", "Melbourne (Australia)", "173"],
    ["19th", "Chicago, Illinois (United States)", "172"],
    ["20th", "Copenhagen (Denmark)", "170"],
    ["21st", "Dublin (Ireland)", "169"],
    ["22nd", "Portland, Oregon (United States)", "169"],
    ["23rd", "Dallas, Texas (United States)", "167"],
    ["24th", "Nassau (Bahamas)", "165"],
    ["25th", "Toronto (Canada)", "163"],
    ["26th", "Sacramento, California (United States)", "163"],
    ["27th", "Paris (France)", "162"],
    ["28th", "Auckland (New Zealand)", "162"],
    ["29th", "Minneapolis - St. Paul, Minnesota (United States)", "162"],
    ["30th", "Austin, Texas (United States)", "162"],
    ["31st", "Amsterdam (Netherlands)", "160"],
    ["32nd", "Philadelphia, Pennsylvania (United States)", "160"],
    ["33rd", "Hong Kong", "159"],
    ["34th", "Orlando, Florida (United States)", "158"],
    ["35th", "Vancouver (Canada)", "155"],
    ["36th", "Oslo (Norway)", "153"],
    ["37th", "Houston, Texas (United States)", "153"],
    ["38th", "Tampa, Florida (United States)", "150"],
    ["39th", "Boise, Idaho (United States)", "149"],
    ["40th", "Tel Aviv (Israel)", "147"],
    ["41st", "Dubai (United Arab Emirates)", "144"],
    ["42nd", "Trondheim (Norway)", "142"],
    ["43rd", "Calgary (Canada)", "141"],
    ["44th", "St. Petersburg, Florida (United States)", "141"],
    ["45th", "Luxembourg", "141"],
    ["46th", "Helsinki (Finland)", "141"],
    ["47th", "Pittsburgh, Pennsylvania (United States)", "141"],
    ["48th", "Wellington (New Zealand)", "141"],
    ["49th", "Baltimore, Maryland (United States)", "140"],
    ["50th", "Stockholm (Sweden)", "140"],
    ["51st", "Newark, New Jersey (United States)", "138"],
    ["52nd", "Manchester (United Kingdom)", "137"],
    ["53rd", "Edinburgh (United Kingdom)", "136"],
    ["54th", "Milan (Italy)", "136"],
    ["55th", "Cleveland, Ohio (United States)", "134"],
    ["56th", "Rotterdam (Netherlands)", "133"],
    ["57th", "Berlin (Germany)", "133"],
    ["58th", "Munich (Germany)", "133"],
    ["59th", "Frankfurt am Main (Germany)", "133"],
    ["60th", "Montreal (Canada)", "132"],
    ["61st", "Brussels (Belgium)", "131"],
    ["62nd", "Doha (Qatar)", "130"],
    ["63rd", "Edmonton (Canada)", "127"],
    ["64th", "Aberdeen (United Kingdom)", "126"],
    ["65th", "San Antonio, Texas (United States)", "125"],
    ["66th", "Santa Fe, New Mexico (United States)", "124"],
    ["67th", "Hamburg (Germany)", "124"],
    ["68th", "Glasgow (United Kingdom)", "124"],
    ["69th", "Cairns (Australia)", "123"],
    ["70th", "Haifa (Israel)", "122"],
    ["71st", "Nice (France)", "122"],
    ["72nd", "Vienna (Austria)", "121"],
    ["73rd", "Abu Dhabi (United Arab Emirates)", "120"],
    ["74th", "Lyon (France)", "119"],
    ["75th", "Montevideo (Uruguay)", "119"],
    ["76th", "Hamilton, New Zealand (New Zealand)", "118"],
    ["77th", "San Sebastian (Spain)", "118"],
    ["78th", "Marseille (France)", "117"],
    ["79th", "Rome (Italy)", "116"],
    ["80th", "Newcastle, Australia (Australia)", "115"],
    ["81st", "Antwerp (Belgium)", "115"],
    ["82nd", "Tallahassee, Florida (United States)", "114"],
    ["83rd", "Valletta (Malta)", "113"],
    ["84th", "Wollongong (Australia)", "111"],
    ["85th", "Grenoble (France)", "111"],
    ["86th", "Ramallah (Palestinian Territory)", "111"],
    ["87th", "Lisbon (Portugal)", "111"],
    ["88th", "Tucson, Arizona (United States)", "110"],
    ["89th", "Madrid (Spain)", "110"],
    ["90th", "Macao", "110"],
    ["91st", "Barcelona, Spain (Spain)", "109"],
    ["92nd", "Tijuana (Mexico)", "109"],
    ["93rd", "Innsbruck (Austria)", "109"],
    ["94th", "Darwin (Australia)", "109"],
    ["95th", "Lille (France)", "108"],
    ["96th", "Nantes (France)", "108"],
    ["97th", "Florence (Italy)", "107"],
    ["98th", "Bergamo (Italy)", "106"],
    ["99th", "Ghent (Belgium)", "105"],
    ["100th", "Dortmund (Germany)", "105"],
    ["101st", "Essen (Germany)", "104"],
    ["102nd", "Oporto (Portugal)", "103"],
    ["103rd", "Bilbao (Spain)", "103"],
    ["104th", "Varese (Italy)", "102"],
    ["105th", "Pamplona (Spain)", "102"],
    ["106th", "Bologna (Italy)", "100"],
    ["107th", "Prague (Czech Republic)", "100"],
    ["108th", "Abbotsford (Canada)", "100"],
    ["109th", "Youngstown, Ohio (United States)", "99"],
    ["110th", "San Jose, Costa Rica (Costa Rica)", "99"],
    ["111th", "Ljubljana (Slovenia)", "98"],
    ["112th", "Dresden (Germany)", "98"],
    ["113th", "Mexico City (Mexico)", "97"],
    ["114th", "Monterrey (Mexico)", "97"],
    ["115th", "Valencia, Spain (Spain)", "97"],
    ["116th", "San Antonio, California (United States)", "96"],
    ["117th", "Ravenna (Italy)", "95"],
    ["118th", "Perugia (Italy)", "95"],
    ["119th", "Amman (Jordan)", "95"],
    ["120th", "Turin (Italy)", "95"],
    ["121st", "Thessaloniki (Greece)", "95"],
    ["122nd", "Zagreb (Croatia)", "94"],
    ["123rd", "Naples (Italy)", "93"],
    ["124th", "Cedar Rapids, Iowa (United States)", "93"],
    ["125th", "Shanghai (China)", "93"],
    ["126th", "Pescara (Italy)", "92"],
    ["127th", "Panama City (Panama)", "92"],
    ["128th", "Taipei (Taiwan)", "91"],
    ["129th", "Warsaw (Poland)", "91"],
    ["130th", "Valladolid (Spain)", "91"],
    ["131st", "Zaragoza (Spain)", "90"],
    ["132nd", "Seville (Spain)", "90"],
    ["133rd", "Corunna (Spain)", "89"],
    ["134th", "Gijón (Spain)", "89"],
    ["135th", "Rio de Janeiro (Brazil)", "88"],
    ["136th", "Santa Cruz de Tenerife (Spain)", "88"],
    ["137th", "Santos, Sao Paulo (Brazil)", "87"],
    ["138th", "Oviedo (Spain)", "87"],
    ["139th", "São Paulo (Brazil)", "87"],
    ["140th", "Las Palmas de Gran Canaria (Spain)", "85"],
    ["141st", "Guadalajara (Mexico)", "85"],
    ["142nd", "Guatemala City (Guatemala)", "85"],
    ["143rd", "Bratislava (Slovakia)", "83"],
    ["144th", "San Salvador (El Salvador)", "83"],
    ["145th", "Caracas (Venezuela)", "82"],
    ["146th", "Beijing (China)", "82"],
    ["147th", "Bangkok (Thailand)", "81"],
    ["148th", "Budapest (Hungary)", "80"],
    ["149th", "Brasília (Brazil)", "80"],
    ["150th", "Almería (Spain)", "80"],
    ["151st", "Santiago, Chile (Chile)", "79"],
    ["152nd", "Belo Horizonte (Brazil)", "78"],
    ["153rd", "Porto Alegre (Brazil)", "78"],
    ["154th", "Georgetown (Guyana)", "77"],
    ["155th", "Lima (Peru)", "76"],
    ["156th", "Moscow (Russia)", "75"],
    ["157th", "Johannesburg (South Africa)", "74"],
    ["158th", "Sofia (Bulgaria)", "74"],
    ["159th", "Medellín (Colombia)", "74"],
    ["160th", "Barquisimeto (Venezuela)", "74"],
    ["161st", "Pula (Croatia)", "73"],
    ["162nd", "Bucharest (Romania)", "73"],
    ["163rd", "Cape Town (South Africa)", "72"],
    ["164th", "Bogotá (Colombia)", "71"],
    ["165th", "Goiânia (Brazil)", "71"],
    ["166th", "Suva (Fiji)", "70"],
    ["167th", "Saint Petersburg (Russia)", "70"],
    ["168th", "Fortaleza (Brazil)", "68"],
    ["169th", "Jakarta (Indonesia)", "66"],
    ["170th", "Pretoria (South Africa)", "66"],
    ["171st", "Nairobi (Kenya)", "64"],
    ["172nd", "Sarajevo (Bosnia and Herzegovina)", "63"],
    ["173rd", "Santiago de Cali (Colombia)", "62"],
    ["174th", "La Paz, Bolivia (Bolivia)", "61"],
    ["175th", "Chengdu (China)", "61"],
    ["176th", "Mumbai (India)", "59"],
    ["177th", "Kuala Lumpur (Malaysia)", "57"],
    ["178th", "Ho Chi Minh City (Vietnam)", "57"],
    ["179th", "Plovdiv (Bulgaria)", "55"],
    ["180th", "Burgas (Bulgaria)", "55"],
    ["181st", "Mostar (Bosnia and Herzegovina)", "54"],
    ["182nd", "Zenica (Bosnia and Herzegovina)", "50"],
    ["183rd", "Delhi (India)", "48"],
    ["184th", "Yogyakarta (Indonesia)", "38"],
];

const citiesData = [];
// ChatGPT generated dict
const country_flags = {
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "Cayman Islands": "🇰🇾",
    Switzerland: "🇨🇭",
    Singapore: "🇸🇬",
    Australia: "🇦🇺",
    Denmark: "🇩🇰",
    Ireland: "🇮🇪",
    Bahamas: "🇧🇸",
    Canada: "🇨🇦",
    France: "🇫🇷",
    "New Zealand": "🇳🇿",
    Netherlands: "🇳🇱",
    "Hong Kong": "🇭🇰",
    Norway: "🇳🇴",
    Israel: "🇮🇱",
    "United Arab Emirates": "🇦🇪",
    Luxembourg: "🇱🇺",
    Finland: "🇫🇮",
    Sweden: "🇸🇪",
    Italy: "🇮🇹",
    Germany: "🇩🇪",
    Belgium: "🇧🇪",
    Qatar: "🇶🇦",
    Austria: "🇦🇹",
    Uruguay: "🇺🇾",
    Spain: "🇪🇸",
    Malta: "🇲🇹",
    "Palestinian Territory": "🇵🇸",
    Portugal: "🇵🇹",
    Macao: "🇲🇴",
    Mexico: "🇲🇽",
    "Czech Republic": "🇨🇿",
    "Costa Rica": "🇨🇷",
    Slovenia: "🇸🇮",
    Jordan: "🇯🇴",
    Greece: "🇬🇷",
    Croatia: "🇭🇷",
    China: "🇨🇳",
    Panama: "🇵🇦",
    Taiwan: "🇹🇼",
    Poland: "🇵🇱",
    Brazil: "🇧🇷",
    Guatemala: "🇬🇹",
    Slovakia: "🇸🇰",
    "El Salvador": "🇸🇻",
    Venezuela: "🇻🇪",
    Thailand: "🇹🇭",
    Hungary: "🇭🇺",
    Chile: "🇨🇱",
    Guyana: "🇬🇾",
    Peru: "🇵🇪",
    Russia: "🇷🇺",
    "South Africa": "🇿🇦",
    Bulgaria: "🇧🇬",
    Colombia: "🇨🇴",
    Romania: "🇷🇴",
    Fiji: "🇫🇯",
    Indonesia: "🇮🇩",
    Kenya: "🇰🇪",
    "Bosnia and Herzegovina": "🇧🇦",
    Bolivia: "🇧🇴",
    India: "🇮🇳",
    Malaysia: "🇲🇾",
    Vietnam: "🇻🇳",
};

citiesNestedArray.forEach((cityArray) => {
    const city_and_country = cityArray[1];
    let city, country;

    if (city_and_country.includes("(")) {
        city = city_and_country.substring(0, city_and_country.indexOf("("));
        country = city_and_country.substring(
            city_and_country.indexOf("(") + 1,
            city_and_country.indexOf(")")
        );
    } else {
        city = city_and_country;
        country = city_and_country;
    }

    const cityDict = {
        ranking: cityArray[0],
        name: city,
        country: country_flags[country],
        priceIndex: parseInt(cityArray[2]),
    };
    citiesData.push(cityDict);
});

citiesData.forEach((city) => {
    console.log(city.country);
});

export default citiesData;
